In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("C:\\Users\\rubig\\Downloads\\victimasFGJ_acumulado_2024_04.csv")
df

,anio_inicio,mes_inicio,fecha_inicio,hora_inicio,anio_hecho,mes_hecho,fecha_hecho,hora_hecho,delito,categoria_delito,...,tipo_persona,calidad_juridica,competencia,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho,latitud,longitud
0,2019.0,Enero,2019-01-04,12:19:00,2018.0,Agosto,2018-08-29,12:00:00,FRAUDE,DELITO DE BAJO IMPACTO,...,FISICA,OFENDIDO,FUERO COMUN,GUADALUPE INN,Guadalupe Inn,ALVARO OBREGON,Álvaro Obregón,CDMX,19.361250,-99.183140
1,2019.0,Enero,2019-01-04,12:20:00,2018.0,Diciembre,2018-12-15,15:00:00,"PRODUCCIÓN, IMPRESIÓN, ENAJENACIÓN, DISTRIBUCI...",DELITO DE BAJO IMPACTO,...,FISICA,VICTIMA Y DENUNCIANTE,FUERO COMUN,VICTORIA DE LAS DEMOCRACIAS,Victoria De Las Democracias,AZCAPOTZALCO,Azcapotzalco,CDMX,19.471810,-99.164580
2,2019.0,Enero,2019-01-04,12:23:00,2018.0,Diciembre,2018-12-22,15:30:00,ROBO A TRANSEUNTE SALIENDO DEL BANCO CON VIOLE...,ROBO A CUENTAHABIENTE SALIENDO DEL CAJERO CON ...,...,FISICA,VICTIMA Y DENUNCIANTE,FUERO COMUN,COPILCO UNIVERSIDAD ISSSTE,Copilco El Bajo,COYOACAN,Coyoacán,CDMX,19.337970,-99.186110
3,2019.0,Enero,2019-01-04,12:27:00,2019.0,Enero,2019-01-04,06:00:00,ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VI...,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,...,FISICA,VICTIMA Y DENUNCIANTE,FUERO COMUN,AGRÍCOLA PANTITLAN,Agricola Pantitlan,IZTACALCO,Iztacalco,CDMX,19.403270,-99.059830
4,2019.0,Enero,2019-01-04,12:35:00,2019.0,Enero,2019-01-03,20:00:00,ROBO DE MOTOCICLETA SIN VIOLENCIA,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,...,FISICA,VICTIMA,FUERO COMUN,PROGRESISTA,Progresista,IZTAPALAPA,Iztapalapa,CDMX,19.354800,-99.063240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311968,2024.0,Marzo,2024-03-22,05:04:40,2024.0,Marzo,2024-03-21,22:10:00,DDH RELACIONADAS,HECHO NO DELICTIVO,...,FISICA,LESIONADO,HECHO NO DELICTIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311969,2024.0,Marzo,2024-03-27,19:22:23,2024.0,Marzo,2024-03-13,12:00:00,DISCRIMINACION,DELITO DE BAJO IMPACTO,...,FISICA,VICTIMA,FUERO COMUN,LINDAVISTA,Lindavista Norte,GUSTAVO A. MADERO,Gustavo A. Madero,CDMX,19.505555,-99.129598
1311970,2024.0,Marzo,2024-03-28,05:46:06,2024.0,Marzo,2024-03-28,03:00:00,FEMINICIDIO POR GOLPES,HOMICIDIO DOLOSO,...,FISICA,CADAVER,FUERO COMUN,NUEVA INDUSTRIAL VALLEJO,Nueva Industrial Vallejo,GUSTAVO A. MADERO,Gustavo A. Madero,CDMX,19.506307,-99.157251
1311971,2024.0,Marzo,2024-03-30,03:20:21,2024.0,Marzo,2024-03-30,10:00:00,LESIONES CULPOSAS POR TRANSITO VEHICULAR,DELITO DE BAJO IMPACTO,...,FISICA,LESIONADO,FUERO COMUN,NaN,NaN,CDMX (indeterminada),CDMX (indeterminada),CDMX,NaN,NaN
1311972,2024.0,Marzo,2024-03-30,22:29:04,2024.0,Marzo,2024-03-01,12:00:00,LA ADMINISTRACION DE JUSTICIA,DELITO DE BAJO IMPACTO,...,MORAL,OFENDIDO,FUERO COMUN,DOCTORES,Doctores,CUAUHTEMOC,Cuauhtémoc,CDMX,19.423694,-99.145833

In [39]:
# Ver nombres de las columnas para eliminar las no necesarias
df.columns

Index(['anio_inicio', 'mes_inicio', 'fecha_inicio', 'hora_inicio',
       'anio_hecho', 'mes_hecho', 'fecha_hecho', 'hora_hecho', 'delito',
       'categoria_delito', 'sexo', 'edad', 'tipo_persona', 'calidad_juridica',
       'competencia', 'colonia_hecho', 'colonia_catalogo', 'alcaldia_hecho',
       'alcaldia_catalogo', 'municipio_hecho', 'latitud', 'longitud'],
      dtype='object')

In [40]:
# Eliminar columnas 
df.drop(columns=['anio_inicio', 'mes_inicio', 'fecha_inicio', 'hora_inicio', 'anio_hecho', 'mes_hecho',
                 'hora_hecho', 'sexo', 'edad', 'tipo_persona', 'calidad_juridica', 'competencia', 'colonia_hecho',
                 'colonia_catalogo', 'alcaldia_hecho', 'alcaldia_catalogo', 'municipio_hecho', 'categoria_delito'], inplace=True)

In [41]:
df

,fecha_hecho,delito,latitud,longitud
0,2018-08-29,FRAUDE,19.361250,-99.183140
1,2018-12-15,"PRODUCCIÓN, IMPRESIÓN, ENAJENACIÓN, DISTRIBUCI...",19.471810,-99.164580
2,2018-12-22,ROBO A TRANSEUNTE SALIENDO DEL BANCO CON VIOLE...,19.337970,-99.186110
3,2019-01-04,ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VI...,19.403270,-99.059830
4,2019-01-03,ROBO DE MOTOCICLETA SIN VIOLENCIA,19.354800,-99.063240
...,...,...,...,...
1311968,2024-03-21,DDH RELACIONADAS,NaN,NaN
1311969,2024-03-13,DISCRIMINACION,19.505555,-99.129598
1311970,2024-03-28,FEMINICIDIO POR GOLPES,19.506307,-99.157251
1311971,2024-03-30,LESIONES CULPOSAS POR TRANSITO VEHICULAR,NaN,NaN
1311972,2024-03-01,LA ADMINISTRACION DE JUSTICIA,19.423694,-99.145833

In [42]:
# Palabra clave para después filtrar por filas los delitos que son robo a negocio
palabra_clave = 'NEGOCIO'

In [43]:
df = df[df['delito'].str.contains(palabra_clave, case=False, na=False)]
df

,fecha_hecho,delito,latitud,longitud
28,2018-12-04,ROBO A NEGOCIO CON VIOLENCIA,19.475760,-99.118190
29,2018-12-04,ROBO A NEGOCIO CON VIOLENCIA,19.475760,-99.118190
38,2019-01-03,ROBO A NEGOCIO CON VIOLENCIA,19.489690,-99.127940
40,2019-01-04,ROBO A NEGOCIO CON VIOLENCIA,19.316700,-99.073340
44,2019-01-04,ROBO A NEGOCIO SIN VIOLENCIA,19.344340,-99.028230
...,...,...,...,...
1311690,2024-04-29,ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS,19.288038,-99.001195
1311696,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIE...,19.337793,-99.184745
1311773,2024-04-27,"ROBO S/V DENTRO DE NEGOCIOS, AUTOSERVICIOS, CO...",19.302757,-99.190125
1311940,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA,19.387815,-99.111903
1311941,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA,19.387815,-99.111903

In [44]:
# Delitos que contienen "robo a negocio"
df['delito'].unique().tolist()

['ROBO A NEGOCIO CON VIOLENCIA',
 'ROBO A NEGOCIO SIN VIOLENCIA',
 'DAÑO EN PROPIEDAD AJENA INTENCIONAL A NEGOCIO',
 'ROBO A NEGOCIO Y VEHICULO CON VIOLENCIA',
 'ROBO A TRANSEUNTE EN NEGOCIO CON VIOLENCIA',
 'ROBO A NEGOCIO Y VEHICULO SIN VIOLENCIA',
 'ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIENDAS DE AUTOSERVICIO)',
 'ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIENDAS DE CONVENIENCIA)',
 'ROBO S/V DENTRO DE NEGOCIOS, AUTOSERVICIOS, CONVENIENCIA',
 'ROBO A NEGOCIO CON VIOLENCIA POR FARDEROS (TIENDAS DE CONVENIENCIA)',
 'ROBO A NEGOCIO CON VIOLENCIA POR FARDEROS (TIENDAS DE AUTOSERVICIO)',
 'ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS',
 'ROBO A NEGOCIO (NOMINA) Y VEHICULO CON VIOLENCIA']

In [45]:
#Renombrar columnas
df.rename(columns={'latitud':'y', 'longitud':'x', 'fecha_hecho':'date_single'}, inplace=True)
df

C:\Users\rubig\AppData\Local\Temp\ipykernel_3968\493477493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'latitud':'y', 'longitud':'x', 'fecha_hecho':'date_single'}, inplace=True)

,date_single,delito,y,x
28,2018-12-04,ROBO A NEGOCIO CON VIOLENCIA,19.475760,-99.118190
29,2018-12-04,ROBO A NEGOCIO CON VIOLENCIA,19.475760,-99.118190
38,2019-01-03,ROBO A NEGOCIO CON VIOLENCIA,19.489690,-99.127940
40,2019-01-04,ROBO A NEGOCIO CON VIOLENCIA,19.316700,-99.073340
44,2019-01-04,ROBO A NEGOCIO SIN VIOLENCIA,19.344340,-99.028230
...,...,...,...,...
1311690,2024-04-29,ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS,19.288038,-99.001195
1311696,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIE...,19.337793,-99.184745
1311773,2024-04-27,"ROBO S/V DENTRO DE NEGOCIOS, AUTOSERVICIOS, CO...",19.302757,-99.190125
1311940,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA,19.387815,-99.111903
1311941,2024-04-30,ROBO A NEGOCIO SIN VIOLENCIA,19.387815,-99.111903

In [47]:
#Descartamos columna de delitos y reordenamos
df = df[['x', 'y', 'date_single']]
df

                 x          y date_single
28      -99.118190  19.475760  2018-12-04
29      -99.118190  19.475760  2018-12-04
38      -99.127940  19.489690  2019-01-03
40      -99.073340  19.316700  2019-01-04
44      -99.028230  19.344340  2019-01-04
...            ...        ...         ...
1311690 -99.001195  19.288038  2024-04-29
1311696 -99.184745  19.337793  2024-04-30
1311773 -99.190125  19.302757  2024-04-27
1311940 -99.111903  19.387815  2024-04-30
1311941 -99.111903  19.387815  2024-04-30

[99488 rows x 3 columns]

In [48]:
df.to_csv('archivo.csv', index=False)